project:
  type: book

book:
  title: "Indicadores para Governança e Gestão da Força de Trabalho em Saúde"
  author: "-"
  date: "-"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - ensino.qmd
    - entrada.qmd
    - manutencao.qmd
    - ambiente.qmd
    - saida.qmd
    - references.qmd
    

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

