# Indicadores de ambiente favorável

## Taxa de mortalidade por homicídios

### Justificativa

### Ficha do indicador

+----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------+
| Nome do Indicador                                                    | Taxa de mortalidade por homicídios                                                                              |
+======================================================================+=================================================================================================================+
| Domínio                                                              | Ambiente favorável                                                                                              |
+----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------+
| Conceitos e definições                                               | Violência no contexto local                                                                                     |
+----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------+
| Método de cálculo                                                    | Numerador: Contagem do número de casos de óbitos de acordo com o CID-10 de X85-Y09 em dada unidade territorial. |
|                                                                      |                                                                                                                 |
|                                                                      | Denominador: número de habitantes do local.                                                                     |
|                                                                      |                                                                                                                 |
|                                                                      | Multiplicador: 100 mil                                                                                          |
+----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------+
| Unidade de medida                                                    | Óbitos por 100 mil habitantes                                                                                   |
+----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------+
| Variáveis que compõem o indicador, fonte e instituições que a produz | Variável:                                                                                                       |
|                                                                      |                                                                                                                 |
|                                                                      | Fonte: Sistema de Informações sobre Mortalidade (SIM) e Projeções populacionais (CGIAE/DAENT/SVS/MS)            |
|                                                                      |                                                                                                                 |
|                                                                      | Instituição:                                                                                                    |
+----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------+
| Abrangência geográfica                                               | Município, UF, região, país                                                                                     |
+----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------+
| Níveis de desagregação indicador                                     | Não se aplica                                                                                                   |
+----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------+
| Periodicidade de atualização do indicador                            | Mensal                                                                                                          |
+----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------+
| Série histórica utilizada                                            |                                                                                                                 |
+----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------+
| Referências                                                          | Montini et al. (2021)                                                                                           |
+----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------+
| Polaridade                                                           | Quanto maior, maiores as taxas de violência                                                                     |
+----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------+

### Calculando o indicador usando R

### Criando uma visualização

## Qualidade da educação nos anos iniciais do ensino fundamental

### Justificativa

### Ficha do indicador

+----------------------------------------------------------------------+------------------------------------------------------------------------------------------+
| Nome do Indicador                                                    | Qualidade da educação nos anos iniciais do ensino fundamental                            |
+======================================================================+==========================================================================================+
| Domínio                                                              | Ambiente favorável                                                                       |
+----------------------------------------------------------------------+------------------------------------------------------------------------------------------+
| Conceitos e definições                                               | Nota do IDEB do município para os anos iniciais (1º ao 5º ano)                           |
+----------------------------------------------------------------------+------------------------------------------------------------------------------------------+
| Método de cálculo                                                    | O indicador já é calculado pelo próprio INEP                                             |
+----------------------------------------------------------------------+------------------------------------------------------------------------------------------+
| Unidade de medida                                                    | Não se aplica                                                                            |
+----------------------------------------------------------------------+------------------------------------------------------------------------------------------+
| Variáveis que compõem o indicador, fonte e instituições que a produz | Variável:                                                                                |
|                                                                      |                                                                                          |
|                                                                      | Fonte: Índice de Desenvolvimento da Educação Básica (Ideb) para os anos iniciais do INEP |
|                                                                      |                                                                                          |
|                                                                      | Instituição:                                                                             |
+----------------------------------------------------------------------+------------------------------------------------------------------------------------------+
| Abrangência geográfica                                               | Município, UF, região, país                                                              |
+----------------------------------------------------------------------+------------------------------------------------------------------------------------------+
| Níveis de desagregação indicador                                     | Não se aplica                                                                            |
+----------------------------------------------------------------------+------------------------------------------------------------------------------------------+
| Periodicidade de atualização do indicador                            | Anual                                                                                    |
+----------------------------------------------------------------------+------------------------------------------------------------------------------------------+
| Série histórica utilizada                                            |                                                                                          |
+----------------------------------------------------------------------+------------------------------------------------------------------------------------------+
| Referências                                                          |                                                                                          |
+----------------------------------------------------------------------+------------------------------------------------------------------------------------------+
| Polaridade                                                           | Quanto maior, melhor a educação local                                                    |
+----------------------------------------------------------------------+------------------------------------------------------------------------------------------+

### Calculando o indicador usando R

### Criando uma visualização

## Qualidade da educação nos anos finais do ensino fundamental

### Justificativa

### Ficha do indicador

+----------------------------------------------------------------------+------------------------------------------------------------------------------------------+
| Nome do Indicador                                                    | Qualidade da educação nos anos finais do ensino fundamental                              |
+======================================================================+==========================================================================================+
| Domínio                                                              | Ambiente favorável                                                                       |
+----------------------------------------------------------------------+------------------------------------------------------------------------------------------+
| Conceitos e definições                                               | Nota do IDEB do município (6º ao 9º ano)                                                 |
+----------------------------------------------------------------------+------------------------------------------------------------------------------------------+
| Método de cálculo                                                    | O indicador já é calculado pelo próprio INEP                                             |
+----------------------------------------------------------------------+------------------------------------------------------------------------------------------+
| Unidade de medida                                                    | Não se aplica                                                                            |
+----------------------------------------------------------------------+------------------------------------------------------------------------------------------+
| Variáveis que compõem o indicador, fonte e instituições que a produz | Variável:                                                                                |
|                                                                      |                                                                                          |
|                                                                      | Fonte: Índice de Desenvolvimento da Educação Básica (Ideb) para os anos iniciais do INEP |
|                                                                      |                                                                                          |
|                                                                      | Instituição:                                                                             |
+----------------------------------------------------------------------+------------------------------------------------------------------------------------------+
| Abrangência geográfica                                               | Município, UF, região, país                                                              |
+----------------------------------------------------------------------+------------------------------------------------------------------------------------------+
| Níveis de desagregação indicador                                     | Não se aplica                                                                            |
+----------------------------------------------------------------------+------------------------------------------------------------------------------------------+
| Periodicidade de atualização do indicador                            | Anual                                                                                    |
+----------------------------------------------------------------------+------------------------------------------------------------------------------------------+
| Série histórica utilizada                                            |                                                                                          |
+----------------------------------------------------------------------+------------------------------------------------------------------------------------------+
| Referências                                                          |                                                                                          |
+----------------------------------------------------------------------+------------------------------------------------------------------------------------------+
| Polaridade                                                           | Quanto maior, melhor a educação local                                                    |
+----------------------------------------------------------------------+------------------------------------------------------------------------------------------+

### Calculando o indicador usando R

### Criando uma visualização

## Densidade de equipamentos por população

### Justificativa

### Ficha do indicador

+----------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------+
| Nome do Indicador                                                    | Densidade de equipamentos por população                                                                                       |
+======================================================================+===============================================================================================================================+
| Domínio                                                              | Ambiente favorável                                                                                                            |
+----------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------+
| Conceitos e definições                                               | Quantidade de equipamentos por 10 mil habitantes de dada localidade                                                           |
+----------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------+
| Método de cálculo                                                    | Numerador: Contagem dos equipamentos Raio-X, Tomógrafo, Ultrassom, Mamógrafo e Ressonância.                                   |
|                                                                      |                                                                                                                               |
|                                                                      | Denominador: número de habitantes do local.                                                                                   |
|                                                                      |                                                                                                                               |
|                                                                      | Multiplicador: 10 mil                                                                                                         |
+----------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------+
| Unidade de medida                                                    | Equipamentos por 10 mil habitantes                                                                                            |
+----------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------+
| Variáveis que compõem o indicador, fonte e instituições que a produz | Variável:                                                                                                                     |
|                                                                      |                                                                                                                               |
|                                                                      | Fonte: Cadastro Nacional de Estabelecimentos de Saúde - Equipamentos (CNES-EQ) e Projeções populacionais (CGIAE/DAENT/SVS/MS) |
|                                                                      |                                                                                                                               |
|                                                                      | Instituição:                                                                                                                  |
+----------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------+
| Abrangência geográfica                                               | Município, UF, região, país                                                                                                   |
+----------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------+
| Níveis de desagregação indicador                                     | Não se aplica                                                                                                                 |
+----------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------+
| Periodicidade de atualização do indicador                            | Mensal                                                                                                                        |
+----------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------+
| Série histórica utilizada                                            |                                                                                                                               |
+----------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------+
| Referências                                                          | Santos et al. (2019),                                                                                                         |
|                                                                      |                                                                                                                               |
|                                                                      | Rocha et al. (2020)                                                                                                           |
+----------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------+
| Polaridade                                                           | Quanto maior, maior a densidade de equipamentos pela população                                                                |
+----------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------+

### Calculando o indicador usando R

### Criando uma visualização

## Vulnerabilidade social

### Justificativa

### Ficha do indicador

+----------------------------------------------------------------------+------------------------------------------------------------------------------------+
| Nome do Indicador                                                    | Vulnerabilidade social                                                             |
+======================================================================+====================================================================================+
| Domínio                                                              | Ambiente favorável                                                                 |
+----------------------------------------------------------------------+------------------------------------------------------------------------------------+
| Conceitos e definições                                               | O GeoSES é um Índice socioeconômico para pesquisas em saúde e sociedade no Brasil. |
+----------------------------------------------------------------------+------------------------------------------------------------------------------------+
| Método de cálculo                                                    | Indicador já calculado                                                             |
+----------------------------------------------------------------------+------------------------------------------------------------------------------------+
| Unidade de medida                                                    | Não se aplica                                                                      |
+----------------------------------------------------------------------+------------------------------------------------------------------------------------+
| Variáveis que compõem o indicador, fonte e instituições que a produz | Variável:                                                                          |
|                                                                      |                                                                                    |
|                                                                      | Fonte: Geoses                                                                      |
|                                                                      |                                                                                    |
|                                                                      | Instituição:                                                                       |
+----------------------------------------------------------------------+------------------------------------------------------------------------------------+
| Abrangência geográfica                                               | Município, UF, região, país                                                        |
+----------------------------------------------------------------------+------------------------------------------------------------------------------------+
| Níveis de desagregação indicador                                     | Não se aplica                                                                      |
+----------------------------------------------------------------------+------------------------------------------------------------------------------------+
| Periodicidade de atualização do indicador                            | Conforme o censo                                                                   |
+----------------------------------------------------------------------+------------------------------------------------------------------------------------+
| Série histórica utilizada                                            |                                                                                    |
+----------------------------------------------------------------------+------------------------------------------------------------------------------------+
| Referências                                                          | Barrozo et al. (2020)                                                              |
+----------------------------------------------------------------------+------------------------------------------------------------------------------------+
| Polaridade                                                           | Quanto maior, menor a vulnerabilidade local                                        |
+----------------------------------------------------------------------+------------------------------------------------------------------------------------+

### Calculando o indicador usando R

### Criando uma visualização
