# Indicadores de Disponibilidade

## Densidade de profissionais habilitados

### Justificativa

### Ficha do indicador

+----------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------+
| Nome do Indicador                                                    | Densidade de profissionais de saúde habilitados                                                               |
+======================================================================+===============================================================================================================+
| Domínio                                                              | Disponibilidade                                                                                               |
+----------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------+
| Conceitos e definições                                               | Quantidade de profissionais habilitados em conselhos profissionais por 10 mil habitantes                      |
+----------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------+
| Método de cálculo                                                    | Numerador: total de profissionais habilitado                                                                  |
|                                                                      |                                                                                                               |
|                                                                      | Denominador: população da unidade territorial                                                                 |
|                                                                      |                                                                                                               |
|                                                                      | Multiplicador: 10 mil                                                                                         |
+----------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------+
| Unidade de medida                                                    | Profissional por 10 mil habitantes                                                                            |
+----------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------+
| Variáveis que compõem o indicador, fonte e instituições que a produz | Variável:                                                                                                     |
|                                                                      |                                                                                                               |
|                                                                      | Fonte: Conselhos de profissões da saúde e projeções populacionais da unidade territorial (CGIAE/DAENT/SVS/MS) |
|                                                                      |                                                                                                               |
|                                                                      | Instituição:                                                                                                  |
+----------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------+
| Abrangência geográfica                                               | UF                                                                                                            |
+----------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------+
| Níveis de desagregação indicador                                     | Categoria profissional                                                                                        |
+----------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------+
| Periodicidade de atualização do indicador                            | Anual, a depender da publicação de números pelos conselhos                                                    |
+----------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------+
| Série histórica utilizada                                            |                                                                                                               |
+----------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------+
| Referências                                                          | Ministério da Saúde (2007)                                                                                    |
+----------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------+
| Polaridade                                                           | Quanto maior, maior densidade de profissionais habilitados                                                    |
+----------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------+

### Calculando o indicador usando R

### Criando uma visualização

## Densidade de profissionais de saúde atuantes

### Justificativa

### Ficha do indicador

+----------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------+
| Nome do Indicador                                                    | Densidade de profissionais de saúde atuantes                                                                                   |
+======================================================================+================================================================================================================================+
| Domínio                                                              | Disponibilidade                                                                                                                |
+----------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------+
| Conceitos e definições                                               | Quantidade de profissionais atuantes em estabelecimentos de saúde por 10 mil habitantes                                        |
+----------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------+
| Método de cálculo                                                    | Numerador: total de profissionais atuantes em estabelecimentos de saúde                                                        |
|                                                                      |                                                                                                                                |
|                                                                      | Denominador: população da unidade territorial                                                                                  |
|                                                                      |                                                                                                                                |
|                                                                      | Multiplicador: 10 mil                                                                                                          |
+----------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------+
| Unidade de medida                                                    | Profissional por 10 mil habitantes                                                                                             |
+----------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------+
| Variáveis que compõem o indicador, fonte e instituições que a produz | Variável:                                                                                                                      |
|                                                                      |                                                                                                                                |
|                                                                      | Fonte: Cadastro Nacional de Estabelecimentos de Saúde - Profissionais (CNES-PF) e Projeções populacionais (CGIAE/DAENT/SVS/MS) |
|                                                                      |                                                                                                                                |
|                                                                      | Instituição:                                                                                                                   |
+----------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------+
| Abrangência geográfica                                               | Município, UF, região, país                                                                                                    |
+----------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------+
| Níveis de desagregação indicador                                     | Categoria profissional                                                                                                         |
+----------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------+
| Periodicidade de atualização do indicador                            | Mensal                                                                                                                         |
+----------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------+
| Série histórica utilizada                                            |                                                                                                                                |
+----------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------+
| Referências                                                          | Ministério da Saúde (2007); OPAS (2020)                                                                                        |
+----------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------+
| Polaridade                                                           | Quanto maior, maios densidade de profissionais atuantes                                                                        |
+----------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------+

### Calculando o indicador usando R

### Criando uma visualização

## Força de trabalho em saúde feminina

### Justificativa

### Ficha do indicador

+----------------------------------------------------------------------+-------------------------------------------------------------------------------------+
| Nome do Indicador                                                    | Força de trabalho em saúde feminina                                                 |
+======================================================================+=====================================================================================+
| Domínio                                                              | Disponibilidade                                                                     |
+----------------------------------------------------------------------+-------------------------------------------------------------------------------------+
| Conceitos e definições                                               | Porcentagem de profissionais de saúde do sexo feminino na força de trabalho atuante |
+----------------------------------------------------------------------+-------------------------------------------------------------------------------------+
| Método de cálculo                                                    | Numerador: total de profissionais do sexo feminino                                  |
|                                                                      |                                                                                     |
|                                                                      | Denominador: total de profissionais de ambos os sexos                               |
+----------------------------------------------------------------------+-------------------------------------------------------------------------------------+
| Unidade de medida                                                    | Porcentagem                                                                         |
+----------------------------------------------------------------------+-------------------------------------------------------------------------------------+
| Variáveis que compõem o indicador, fonte e instituições que a produz | Variável:                                                                           |
|                                                                      |                                                                                     |
|                                                                      | Fonte: Cadastro Nacional de Estabelecimentos de Saúde - Profissionais (CNES-PF)     |
|                                                                      |                                                                                     |
|                                                                      | Instituição:                                                                        |
+----------------------------------------------------------------------+-------------------------------------------------------------------------------------+
| Abrangência geográfica                                               | Município, UF, região, país                                                         |
+----------------------------------------------------------------------+-------------------------------------------------------------------------------------+
| Níveis de desagregação indicador                                     | Categoria profissional                                                              |
+----------------------------------------------------------------------+-------------------------------------------------------------------------------------+
| Periodicidade de atualização do indicador                            | Mensal                                                                              |
+----------------------------------------------------------------------+-------------------------------------------------------------------------------------+
| Série histórica utilizada                                            |                                                                                     |
+----------------------------------------------------------------------+-------------------------------------------------------------------------------------+
| Referências                                                          | OPAS (2020)                                                                         |
+----------------------------------------------------------------------+-------------------------------------------------------------------------------------+
| Polaridade                                                           | Quanto maior, maior participação feminina                                           |
+----------------------------------------------------------------------+-------------------------------------------------------------------------------------+

### Calculando o indicador usando R

### Criando uma visualização

## Força de trabalho em equivalente tempo integral (full-time equivalent)

### Justificativa

### Ficha do indicador

+----------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Nome do Indicador                                                    | Força de trabalho em equivalente tempo integral (full-time equivalent)                                                                                                                                              |
+======================================================================+=====================================================================================================================================================================================================================+
| Domínio                                                              | Disponibilidade                                                                                                                                                                                                     |
+----------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Conceitos e definições                                               | Quantidade de profissionais usando uma métrica chamada equivalente tempo integral, calculada com base nas cargas horárias                                                                                           |
+----------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Método de cálculo                                                    | Numerador: Somatório das variáveis sobre carga horária semanal - carga horária hospitalar, carga horária ambulatorial e carga horária outros - de dada categoria profissional para uma unidade territorial definida |
|                                                                      |                                                                                                                                                                                                                     |
|                                                                      | Denominador: carga horária integral padrão, 40h                                                                                                                                                                     |
+----------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Unidade de medida                                                    | Equivalente tempo integral (ETI) ou Full-time equivalent (FTE). Corresponde ao número de profissionais em tempo integral                                                                                            |
+----------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Variáveis que compõem o indicador, fonte e instituições que a produz | Variável:                                                                                                                                                                                                           |
|                                                                      |                                                                                                                                                                                                                     |
|                                                                      | Fonte: Cadastro Nacional de Estabelecimentos de Saúde - Profissionais (CNES-PF)                                                                                                                                     |
|                                                                      |                                                                                                                                                                                                                     |
|                                                                      | Instituição:                                                                                                                                                                                                        |
+----------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Abrangência geográfica                                               | Município, UF, região, país                                                                                                                                                                                         |
+----------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Níveis de desagregação indicador                                     | Categoria profissional, tipo de vínculo (SUS ou não SUS), nível de atenção (atenção primária, secundária, terciária)                                                                                                |
+----------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Periodicidade de atualização do indicador                            | Mensal                                                                                                                                                                                                              |
+----------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Série histórica utilizada                                            |                                                                                                                                                                                                                     |
+----------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Referências                                                          | Ministério da Saúde (2007)                                                                                                                                                                                          |
+----------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Polaridade                                                           | Quanto maior, maior a disponibilidade da força de trabalho em saúde                                                                                                                                                 |
+----------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

### Calculando o indicador usando R

### Criando uma visualização

## Média de Idade dos profissionais de saúde

### Justificativa

### Ficha do indicador

+----------------------------------------------------------------------+--------------------------------------------------------------------------------------------------+
| Nome do Indicador                                                    | Média de Idade dos profissionais de saúde                                                        |
+======================================================================+==================================================================================================+
| Domínio                                                              | Disponibilidade                                                                                  |
+----------------------------------------------------------------------+--------------------------------------------------------------------------------------------------+
| Conceitos e definições                                               | Média de Idade dos profissionais de saúde                                                        |
+----------------------------------------------------------------------+--------------------------------------------------------------------------------------------------+
| Método de cálculo                                                    | Média da variável de idade de determinada categoria profissional na unidade territorial definida |
+----------------------------------------------------------------------+--------------------------------------------------------------------------------------------------+
| Unidade de medida                                                    | Anos                                                                                             |
+----------------------------------------------------------------------+--------------------------------------------------------------------------------------------------+
| Variáveis que compõem o indicador, fonte e instituições que a produz | Variável:                                                                                        |
|                                                                      |                                                                                                  |
|                                                                      | Fonte: Pesquisa Nacional por Amostra de Domicílios Contínua (PNADc - IBGE)                       |
|                                                                      |                                                                                                  |
|                                                                      | Instituição:                                                                                     |
+----------------------------------------------------------------------+--------------------------------------------------------------------------------------------------+
| Abrangência geográfica                                               | Estadual                                                                                         |
+----------------------------------------------------------------------+--------------------------------------------------------------------------------------------------+
| Níveis de desagregação indicador                                     | Categoria profissional                                                                           |
+----------------------------------------------------------------------+--------------------------------------------------------------------------------------------------+
| Periodicidade de atualização do indicador                            | Trimestral                                                                                       |
+----------------------------------------------------------------------+--------------------------------------------------------------------------------------------------+
| Série histórica utilizada                                            |                                                                                                  |
+----------------------------------------------------------------------+--------------------------------------------------------------------------------------------------+
| Referências                                                          | OPAS (2020)                                                                                      |
+----------------------------------------------------------------------+--------------------------------------------------------------------------------------------------+
| Polaridade                                                           | Não se aplica                                                                                    |
+----------------------------------------------------------------------+--------------------------------------------------------------------------------------------------+

### Calculando o indicador usando R

### Criando uma visualização
