# Indicadores de Ensino

Aqui estão apresentadas as variáveis relacionadas ao ensino.

## Quantidade de cursos de saúde

### Justificativa

### Ficha do indicador

+----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------+
| Nome do Indicador                                                    | Quantidade de cursos de saúde                                                                             |
+======================================================================+===========================================================================================================+
| Domínio                                                              | Ensino                                                                                                    |
+----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------+
| Conceitos e definições                                               | Quantidade de cursos para ensino e treinamento em saúde                                                   |
+----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------+
| Método de cálculo                                                    | Somatório da quantidade de cursos de saúde de dada unidade territorial                                    |
+----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------+
| Unidade de medida                                                    | Cursos                                                                                                    |
+----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------+
| Variáveis que compõem o indicador, fonte e instituições que a produz | Variável:                                                                                                 |
|                                                                      |                                                                                                           |
|                                                                      | Fonte: Censo da Educação Superior (INEP)                                                                  |
|                                                                      |                                                                                                           |
|                                                                      | Instituição:                                                                                              |
+----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------+
| Abrangência geográfica                                               | Município, UF, região, país                                                                               |
+----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------+
| Níveis de desagregação indicador                                     | Curso superior, rede de ensino (público privado), grau acadêmico (bachalerado, tecnológico, licenciatura) |
+----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------+
| Periodicidade de atualização do indicador                            | Anual                                                                                                     |
+----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------+
| Série histórica utilizada                                            |                                                                                                           |
+----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------+
| Referências                                                          | Ministério da Saúde (2007)                                                                                |
+----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------+
| Polaridade                                                           | Quanto maior, maior quantidade de cursos na localidade                                                    |
+----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------+

### Calculando o indicador usando R

### Criando uma visualização

## Percentual de cursos EaD em saúde

### Justificativa

### Ficha do indicador

+----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------+
| Nome do Indicador                                                    | Percentual de cursos EaD em saúde                                                                         |
+======================================================================+===========================================================================================================+
| Domínio                                                              | Ensino                                                                                                    |
+----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------+
| Conceitos e definições                                               | Percentual de cursos no formato EaD na área de saúde                                                      |
+----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------+
| Método de cálculo                                                    | Numerador: Total de cursos da modalidade EaD                                                              |
|                                                                      |                                                                                                           |
|                                                                      | Denominador: total de cursos independente de modalidade                                                   |
+----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------+
| Unidade de medida                                                    | Porcentagem                                                                                               |
+----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------+
| Variáveis que compõem o indicador, fonte e instituições que a produz | Variável:                                                                                                 |
|                                                                      |                                                                                                           |
|                                                                      | Fonte: Censo da Educação Superior (INEP)                                                                  |
|                                                                      |                                                                                                           |
|                                                                      | Instituição:                                                                                              |
+----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------+
| Abrangência geográfica                                               | Município, UF, região, país                                                                               |
+----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------+
| Níveis de desagregação indicador                                     | Curso superior, rede de ensino (público privado), grau acadêmico (bachalerado, tecnológico, licenciatura) |
+----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------+
| Periodicidade de atualização do indicador                            | Anual                                                                                                     |
+----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------+
| Série histórica utilizada                                            |                                                                                                           |
+----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------+
| Referências                                                          |                                                                                                           |
+----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------+
| Polaridade                                                           | Quanto maior, maior participação de EaD formando profissionais de saúde                                   |
+----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------+

### Calculando o indicador usando R

### Criando uma visualização

## Quantidade de vagas oferecidas em cursos da saúde

### Justificativa

### Ficha do indicador

+----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------+
| Nome do Indicador                                                    | Quantidade de vagas oferecidas em cursos da saúde                                                         |
+======================================================================+===========================================================================================================+
| Domínio                                                              | Ensino                                                                                                    |
+----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------+
| Conceitos e definições                                               | Oferta de vagas em cursos superiores da saúde                                                             |
+----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------+
| Método de cálculo                                                    | Somatório da quantidade de vagas ofertadas em cursos de saúde de dada unidade territorial                 |
+----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------+
| Unidade de medida                                                    | Vagas                                                                                                     |
+----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------+
| Variáveis que compõem o indicador, fonte e instituições que a produz | Variável:                                                                                                 |
|                                                                      |                                                                                                           |
|                                                                      | Fonte: Censo da Educação Superior (INEP)                                                                  |
|                                                                      |                                                                                                           |
|                                                                      | Instituição:                                                                                              |
+----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------+
| Abrangência geográfica                                               | Município, UF, região, país                                                                               |
+----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------+
| Níveis de desagregação indicador                                     | Curso superior, rede de ensino (público privado), grau acadêmico (bachalerado, tecnológico, licenciatura) |
+----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------+
| Periodicidade de atualização do indicador                            | Anual                                                                                                     |
+----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------+
| Série histórica utilizada                                            |                                                                                                           |
+----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------+
| Referências                                                          |                                                                                                           |
+----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------+
| Polaridade                                                           | Quanto maior, maior quantidade de vagas de dada localidade                                                |
+----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------+

### Calculando o indicador usando R

### Criando uma visualização

## Quantidade de alunos inscritos em cursos da saúde

### Justificativa

### Ficha do indicador

+----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------+
| Nome do Indicador                                                    | Quantidade de alunos inscritos em cursos da saúde                                                         |
+======================================================================+===========================================================================================================+
| Domínio                                                              | Ensino                                                                                                    |
+----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------+
| Conceitos e definições                                               | Quantidade de alunos inscritos em cursos superiores da saúde                                              |
+----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------+
| Método de cálculo                                                    | Somatório da quantidade de alunos inscritos em cursos de saúde de dada unidade territorial                |
+----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------+
| Unidade de medida                                                    | Aluno inscritos                                                                                           |
+----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------+
| Variáveis que compõem o indicador, fonte e instituições que a produz | Variável:                                                                                                 |
|                                                                      |                                                                                                           |
|                                                                      | Fonte: Censo da Educação Superior (INEP)                                                                  |
|                                                                      |                                                                                                           |
|                                                                      | Instituição:                                                                                              |
+----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------+
| Abrangência geográfica                                               | Município, UF, região, país                                                                               |
+----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------+
| Níveis de desagregação indicador                                     | Curso superior, rede de ensino (público privado), grau acadêmico (bachalerado, tecnológico, licenciatura) |
+----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------+
| Periodicidade de atualização do indicador                            | Anual                                                                                                     |
+----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------+
| Série histórica utilizada                                            |                                                                                                           |
+----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------+
| Referências                                                          |                                                                                                           |
+----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------+
| Polaridade                                                           | Quanto maior, maior quantidade de alunos inscritos                                                        |
+----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------+

### Calculando o indicador usando R

### Criando uma visualização

## Quantidade de alunos ingressantes em cursos da saúde

### Justificativa

### Ficha do indicador

+----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------+
| Nome do Indicador                                                    | Quantidade de alunos ingressantes em cursos da saúde                                                      |
+======================================================================+===========================================================================================================+
| Domínio                                                              | Ensino                                                                                                    |
+----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------+
| Conceitos e definições                                               | Quantidade de alunos ingressantes em cursos superiores da saúde                                           |
+----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------+
| Método de cálculo                                                    | Somatório da quantidade de alunos ingressantes em cursos de saúde de dada unidade territorial             |
+----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------+
| Unidade de medida                                                    | Alunos ingressantes                                                                                       |
+----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------+
| Variáveis que compõem o indicador, fonte e instituições que a produz | Variável:                                                                                                 |
|                                                                      |                                                                                                           |
|                                                                      | Fonte: Censo da Educação Superior (INEP)                                                                  |
|                                                                      |                                                                                                           |
|                                                                      | Instituição:                                                                                              |
+----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------+
| Abrangência geográfica                                               | Município, UF, região, país                                                                               |
+----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------+
| Níveis de desagregação indicador                                     | Curso superior, rede de ensino (público privado), grau acadêmico (bachalerado, tecnológico, licenciatura) |
+----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------+
| Periodicidade de atualização do indicador                            | Anual                                                                                                     |
+----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------+
| Série histórica utilizada                                            |                                                                                                           |
+----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------+
| Referências                                                          |                                                                                                           |
+----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------+
| Polaridade                                                           | Quanto maior, maior quantidade de alunos ingressantes                                                     |
+----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------+

### Calculando o indicador usando R

### Criando uma visualização

## Quantidade de alunos concluintes em cursos da saúde

### Justificativa

### Ficha do indicador

+----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------+
| Nome do Indicador                                                    | Quantidade de alunos concluintes em cursos da saúde                                                       |
+======================================================================+===========================================================================================================+
| Domínio                                                              | Ensino                                                                                                    |
+----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------+
| Conceitos e definições                                               | Quantidade de alunos concluintes em cursos superiores da saúde                                            |
+----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------+
| Método de cálculo                                                    | Somatório da quantidade de alunos concluintes em cursos de saúde de dada unidade territorial              |
+----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------+
| Unidade de medida                                                    | Alunos concluintes                                                                                        |
+----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------+
| Variáveis que compõem o indicador, fonte e instituições que a produz | Variável:                                                                                                 |
|                                                                      |                                                                                                           |
|                                                                      | Fonte: Censo da Educação Superior (INEP)                                                                  |
|                                                                      |                                                                                                           |
|                                                                      | Instituição:                                                                                              |
+----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------+
| Abrangência geográfica                                               | Município, UF, região, país                                                                               |
+----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------+
| Níveis de desagregação indicador                                     | Curso superior, rede de ensino (público privado), grau acadêmico (bachalerado, tecnológico, licenciatura) |
+----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------+
| Periodicidade de atualização do indicador                            | Anual                                                                                                     |
+----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------+
| Série histórica utilizada                                            |                                                                                                           |
+----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------+
| Referências                                                          |                                                                                                           |
+----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------+
| Polaridade                                                           | Quanto maior, maior quantidade de alunos concluintes                                                      |
+----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------+

### Calculando o indicador usando R

### Criando uma visualização

## Razão de alunos inscritos por vaga em cursos de saúde

### Justificativa

### Ficha do indicador

+----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------+
| Nome do Indicador                                                    | Razão de alunos inscritos por vaga em cursos de saúde                                                     |
+======================================================================+===========================================================================================================+
| Domínio                                                              | Ensino                                                                                                    |
+----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------+
| Conceitos e definições                                               | Razão do número de alunos inscritos pelo número total de vagas ofertadas                                  |
+----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------+
| Método de cálculo                                                    | Numerador: Quantidade de alunos inscritos                                                                 |
|                                                                      |                                                                                                           |
|                                                                      | Denominador: total de vagas ofertadas                                                                     |
+----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------+
| Unidade de medida                                                    | Não se aplica                                                                                             |
+----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------+
| Variáveis que compõem o indicador, fonte e instituições que a produz | Variável:                                                                                                 |
|                                                                      |                                                                                                           |
|                                                                      | Fonte: Censo da Educação Superior (INEP)                                                                  |
|                                                                      |                                                                                                           |
|                                                                      | Instituição:                                                                                              |
+----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------+
| Abrangência geográfica                                               | Município, UF, região, país                                                                               |
+----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------+
| Níveis de desagregação indicador                                     | Curso superior, rede de ensino (público privado), grau acadêmico (bachalerado, tecnológico, licenciatura) |
+----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------+
| Periodicidade de atualização do indicador                            | Anual                                                                                                     |
+----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------+
| Série histórica utilizada                                            |                                                                                                           |
+----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------+
| Referências                                                          |                                                                                                           |
+----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------+
| Polaridade                                                           | Quanto maior, maior a concorrência pelas vagas disponíveis                                                |
+----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------+

### Calculando o indicador usando R

### Criando uma visualização

## Taxa de graduados em cursos de saúde

### Justificativa

### Ficha do indicador

+----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------+
| Nome do Indicador                                                    | Taxa de graduados em cursos de saúde                                                                            |
+======================================================================+=================================================================================================================+
| Domínio                                                              | Ensino                                                                                                          |
+----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------+
| Conceitos e definições                                               | Razão entre o total de alunos que concluíram o curso pelo total de alunos ingressantes no primeiro ano do curso |
+----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------+
| Método de cálculo                                                    | Numerador: Quantidade de alunos concluintes                                                                     |
|                                                                      |                                                                                                                 |
|                                                                      | Denominador: total de ingressantes no primeiro ano do curso                                                     |
+----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------+
| Unidade de medida                                                    | Não se aplica                                                                                                   |
+----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------+
| Variáveis que compõem o indicador, fonte e instituições que a produz | Variável:                                                                                                       |
|                                                                      |                                                                                                                 |
|                                                                      | Fonte: Censo da Educação Superior (INEP)                                                                        |
|                                                                      |                                                                                                                 |
|                                                                      | Instituição:                                                                                                    |
+----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------+
| Abrangência geográfica                                               | Município, UF, região, país                                                                                     |
+----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------+
| Níveis de desagregação indicador                                     | Curso superior, rede de ensino (público privado), grau acadêmico (bachalerado, tecnológico, licenciatura)       |
+----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------+
| Periodicidade de atualização do indicador                            | Anual                                                                                                           |
+----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------+
| Série histórica utilizada                                            |                                                                                                                 |
+----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------+
| Referências                                                          |                                                                                                                 |
+----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------+
| Polaridade                                                           | Quanto maior, maior a reposição de alunos no processo de formação                                               |
+----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------+

### Calculando o indicador usando R

### Criando uma visualização

## Qualidade de cursos de educação superior

### Justificativa

### Ficha do indicador

+----------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------+
| Nome do Indicador                                                    | Qualidade de cursos de educação superior                                                                                           |
+======================================================================+====================================================================================================================================+
| Domínio                                                              | Ensino                                                                                                                             |
+----------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------+
| Conceitos e definições                                               | Notas de alunos no Exame Nacional de Desempenho dos Estudantes (ENADE)                                                             |
+----------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------+
| Método de cálculo                                                    | Média das notas de cursos superiores avaliados pelo Exame Nacional de Desempenho dos Estudantes (ENADE) de dado curso e localidade |
+----------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------+
| Unidade de medida                                                    | Não se aplica                                                                                                                      |
+----------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------+
| Variáveis que compõem o indicador, fonte e instituições que a produz | Variável:                                                                                                                          |
|                                                                      |                                                                                                                                    |
|                                                                      | Fonte: ENADE                                                                                                                       |
|                                                                      |                                                                                                                                    |
|                                                                      | Instituição:                                                                                                                       |
+----------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------+
| Abrangência geográfica                                               | Município, UF, região, país                                                                                                        |
+----------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------+
| Níveis de desagregação indicador                                     | Curso superior, rede de ensino (público privado), grau acadêmico (bachalerado, tecnológico, licenciatura)                          |
+----------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------+
| Periodicidade de atualização do indicador                            | A depender do ciclo de avaliação de cursos                                                                                         |
+----------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------+
| Série histórica utilizada                                            |                                                                                                                                    |
+----------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------+
| Referências                                                          |                                                                                                                                    |
+----------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------+
| Polaridade                                                           | Quanto maior, maior a qualidade dos cursos                                                                                         |
+----------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------+

### Calculando o indicador usando R

### Criando uma visualização
