# Entrada no mercado de trabalho

## Atuação da força de trabalho habilitada

### Justificativa

### Ficha do indicador

+----------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------+
| Nome do Indicador                                                    | Percentual de força de trabalho habilitada atuando em estabelecimentos de saúde                                    |
+======================================================================+====================================================================================================================+
| Domínio                                                              | Entrada no mercado de trabalho                                                                                     |
+----------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------+
| Conceitos e definições                                               | Volume de profissionais habilitados que estão atuando em estabelecimentos de saúde                                 |
+----------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------+
| Método de cálculo                                                    | Numerador: total de profissionais atuantes em estabelecimentos de saúde conforme CNES                              |
|                                                                      |                                                                                                                    |
|                                                                      | Denominador: total de profissionais habilitados conforme conselhos profissionais                                   |
+----------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------+
| Unidade de medida                                                    | Porcentagem                                                                                                        |
+----------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------+
| Variáveis que compõem o indicador, fonte e instituições que a produz | Variável:                                                                                                          |
|                                                                      |                                                                                                                    |
|                                                                      | Fonte: Conselhos de profissões de saúde e Cadastro nacional de estabelecimentos de saúde - Profissionais (CNES-PF) |
|                                                                      |                                                                                                                    |
|                                                                      | Instituição:                                                                                                       |
+----------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------+
| Abrangência geográfica                                               | UF                                                                                                                 |
+----------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------+
| Níveis de desagregação indicador                                     | Categoria profissional                                                                                             |
+----------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------+
| Periodicidade de atualização do indicador                            | Anual, a depender da publicação de números pelos conselhos                                                         |
+----------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------+
| Série histórica utilizada                                            |                                                                                                                    |
+----------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------+
| Referências                                                          | OPAS (2020)                                                                                                        |
+----------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------+
| Polaridade                                                           | Quanto maior, maior emprego da força de trabalho habilitada em estabelecimentos de saúde                           |
+----------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------+

### Calculando o indicador usando R

### Criando uma visualização
