# Indicadores de saída

## Taxa de retenção de profissionais localizados em região de saúde

### Justificativa

### Ficha do indicador

+----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------+
| Nome do Indicador                                                    | Taxa de retenção de profissionais localizados em região de saúde                                                            |
+======================================================================+=============================================================================================================================+
| Domínio                                                              | Saída                                                                                                                       |
+----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------+
| Conceitos e definições                                               | Taxa de profissionais atuantes em estabelecimentos de saúde ao longo do tempo                                               |
+----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------+
| Método de cálculo                                                    | Análise de coorte dos profissionais que permanecem em dada unidade territorial ao longo de um horizonte temporal de 10 anos |
+----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------+
| Unidade de medida                                                    | Porcentagem                                                                                                                 |
+----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------+
| Variáveis que compõem o indicador, fonte e instituições que a produz | Variável:                                                                                                                   |
|                                                                      |                                                                                                                             |
|                                                                      | Fonte: Cadastro Nacional de Estabelecimentos de Saúde - Profissionais (CNES-PF)                                             |
|                                                                      |                                                                                                                             |
|                                                                      | Instituição:                                                                                                                |
+----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------+
| Abrangência geográfica                                               | Região de Saúde                                                                                                             |
+----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------+
| Níveis de desagregação indicador                                     | Categoria profissional                                                                                                      |
+----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------+
| Periodicidade de atualização do indicador                            | Anual                                                                                                                       |
+----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------+
| Série histórica utilizada                                            |                                                                                                                             |
+----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------+
| Referências                                                          |                                                                                                                             |
+----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------+
| Polaridade                                                           | Quanto maior, maior a taxa de retenção de profissionais no local                                                            |
+----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------+

### Calculando o indicador usando R

### Criando uma visualização
